import Head from "next/head";
import HeroSection from "../components/HeroSection";
import Navbar from "../components/Navbar";
import CustomCursor from "../components/CustomCursor";
import AboutSection from "../components/AboutSection";
import SkillsSection from "../components/SkillsSection";
import WorksSection from "../components/WorksSection";
import ContactSection from "../components/ContactSection";
import Loader from "../components/Loader";
import { useEffect, useState } from "react";

export default function Home() {
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    setLoading(true);
    setTimeout(() => {
      setLoading(false);
    }, 4000);
  }, []);

  return (
    <div>
      <Head>
        <title>Aman Janwani</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://res.cloudinary.com/dfk5jbk5r/image/upload/v1639398172/profilepic2_2_1_l6iu0d.png"
        />
      </Head>
      <CustomCursor />
      {loading ? (
        <Loader />
      ) : (
        <main>
          <Navbar />
          <HeroSection />
          <AboutSection />
          <SkillsSection />
          <WorksSection />
          <ContactSection />
        </main>
      )}
    </div>
  );
}
